version: "3.7"
services: 
  puppeteer:
    build:
      context: ./
      dockerfile: Dockerfile
    image: puppeteer
    container_name: puppeteer
    volumes:
      - ./src:/puppeteer/src
    command: node /puppeteer/src/app.js
